### PR TITLE
Add kakkoyun to OWNERS

### PR DESCRIPTION
**Pull request by kakkoyun**
This PR shamelessly propose myself as an owner.

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

### CODE REVIEW

**Comment by paulfantom** [comment]
o.0 I am an approver :smile:

**Comment by kakkoyun** [comment]
@metalmatze  🤔 Is this file even relevant?

**Comment by paulfantom** [comment]
> Is this file even relevant?

No, it is not relevant in @thanos-io. This file is necessary in kubernetes org and orgs which use Prow as a CI tool.

**Comment by kakkoyun** [comment]
Then I'll close this one and remove that file in another PR.

**Pull request closed without merging**
