### PR TITLE
All missing liveness and readiness probes

### LINKED ISSUE #34: Add healthcheck probes
The containers are missing liveness/readiness probes. 

As its a Kubernetes best-practice, we should get them added. 

I can work on it once I figure out my `jb` crashing locally :)

### PR DESCRIPTION
**Pull request by kakkoyun**
Fixes #34 

This is waiting for upstream Thanos changes to be merged, https://github.com/thanos-io/thanos/pull/1534, https://github.com/thanos-io/thanos/pull/1460, https://github.com/thanos-io/thanos/pull/1537, https://github.com/thanos-io/thanos/pull/1538 and https://github.com/thanos-io/thanos/pull/1540.

### CODE REVIEW

**Comment by kakkoyun** [comment]
@metalmatze All the dependent PRs are merged, we're good to go with this.

**Comment by metalmatze** [comment]
Not sure I want to introduce `quay.io/thanos/thanos:master-2019-09-23-7a2f54e8'` as image. Maybe this PR needs to wait until we have a new Thanos release?!

**Comment by kakkoyun** [comment]
@metalmatze Good idea, let's wait

**Comment by kakkoyun** [comment]
@metalmatze The stable version of Thanos released https://github.com/thanos-io/thanos/releases/tag/v0.8.0 🎉 We're good to go with this one!

**Pull request merged**
