### PR TITLE
Create SA instead of using default sa

### PR DESCRIPTION
**Pull request by clyang82**
Create the SA for each component instead of using default serviceaccount.
Have tested in my local environment with observatorium operator.

### CODE REVIEW

**Comment by metalmatze** [comment]
I don't think we need separate ones for each component, but rather one for all Thanos components? What's the improvement to have multiple?

**Comment by clyang82** [comment]
@metalmatze Thanks for looking at.
I am not sure if we have the case that the different component requests the different permission. Separate one for each component is to make it flexible and extendable in the future. for example: right now, the thanos-receiver-controller need to have permission to list/watch configmap and statefulset, while other components do not have such requirement.

**Comment by metalmatze** [comment]
That makes sense. As the Thanos Receive Controller is not part of upstream Thanos (yet), nor part of this repository - I don't think we have the need to separate these ServiceAccounts for each and every component prematurely. I'm all for it once we really have the need to do it.
I don't think any of these components in kube-thanos talk to the Thanos API at all.
So either using the default ServiceAccount or a specific one to make it slightly more explicit, seems enough for now.

**Comment by clyang82** [comment]
@metalmatze Thanks for your comments. Just updated with `withServiceAccount`, Let consumer to provide the serviceAccount if needed.

**Comment by metalmatze** [comment]
Where do people create the ServiceAccount now? Is that done on the outside?

**Comment by clyang82** [comment]
@metalmatze the user who will use the components can provide the ServiceAccount. For our case, the ServiceAccount will be created in observatorium component. Does it make sense? Thanks.

**Comment by metalmatze** [comment]
I'd prefer to just add the specific ServiceAccount by default and have that set as default. That makes the most sense for the kube-thanos project.
We specifically use jsonnet to overwrite whatever parts necessary downstream.

**Comment by clyang82** [comment]
Close it in favor of https://github.com/observatorium/deployments/pull/343

**Pull request closed without merging**
