### PR TITLE
cut release v0.24.0

### PR DESCRIPTION
**Pull request by prashbnair**
PR for releasing 0.24.0

### CODE REVIEW

**Review by kakkoyun — COMMENTED** [review]
Apparently, we have released v0.23.0 but the changelog hasn't been updated. Would you also take care of that as part of this?

https://github.com/thanos-io/kube-thanos/releases/tag/v0.23.0

@prashbnair

**Comment by prashbnair** [comment]
@kakkoyun release 0.23 is not a valid release as the version was not updated in them, I am not sure if we still need to track it in the changelog.

**Comment by matej-g** [comment]
Hey @prashbnair, has the `0.24.0` been finalized? I don't see it in the release page https://github.com/thanos-io/kube-thanos/releases.

**Comment by prashbnair** [comment]
I did not cut a release branch, I only made the changes required for release and merged it to main branch.

**Comment by peikk0** [comment]
Hi @prashbnair, would you be able to tag and publish a release for this version? The last one published is still v0.23.0.

**Comment by matej-g** [comment]
I think @raptorsun is on it :muscle:

**Pull request merged**
