### PR TITLE
enforce ReadWriteOnce

### PR DESCRIPTION
**Pull request by clyang82**
Address the comment  - https://github.com/observatorium/deployments/pull/389#issuecomment-797358595

/assign @brancz 

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by brancz** [comment]
Nice! Does this still work even if the volumeClaimTemplate is unset?

**Comment by clyang82** [comment]
volumeClaimTemplate is required field for `operator`. in `deployment`, I think we have the default value.

**Comment by brancz** [comment]
It's not required for all uses of kube-thanos though, some people may choose not to have volumes. I think it would be sufficient to just check that it exists _and if so_ that the access mode is ReadWriteOnce.

**Comment by brancz** [comment]
Nice!

**Comment by brancz** [comment]
lgtm

**Pull request merged**
