### PR TITLE
fix: receive router deployment selector labels

### PR DESCRIPTION
**Pull request by dschaaff**
The pod selector labels on the receive router deployment include the version label. Selector labels are immutable and this prevents updating the receive router.

```
Deployment/monitoring/thanos-receive-router dry-run failed, reason: Invalid, error: Deployment.apps "thanos-receive-router" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"thanos-receive-router", "app.kubernetes.io/instance":"thanos-receive", "app.kubernetes.io/name":"thanos-receive", "app.kubernetes.io/version":"v0.30.2"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

Signed-off-by: Daniel Schaaff <daniel@danielschaaff.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by douglascamata** [comment]
@michael-burt out of all the people you pinged, only @metalmatze is a maintainer, but he hasn't been active in the project. The others are just contributors (like @philipgough) or triagers (like me), without merge rights. Please ask for a review in the #thanos-dev channel in the CNCF slack, that's the right place.

**Comment by douglascamata** [comment]
I can review and approve, but I can't merge.

**Review by douglascamata — APPROVED** [review]

**Comment by douglascamata** [comment]
Also, Github is telling me that there are conflicts in this branch that must be solved.

**Comment by dschaaff** [comment]
I've resolved the conflicts

**Comment by yeya24** [comment]
Thanks

**Pull request merged**
