### PR TITLE
ci: Validate custom resources

### PR DESCRIPTION
**Pull request by maxbrunet**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

* Validate ServiceMonitor schema and remove `--ignore-missing-schemas`
* ~Force color output ✨~ No colors with `kubeconform`
* Validate against up-to-date Kubernetes schema
* Fix Sidecar ServiceMonitor (I found an issue in my own changes 😅)

```
WARN - examples/all/manifests/thanos-sidecar-serviceMonitor.yaml contains an invalid ServiceMonitor (thanos.thanos-sidecar) - relabelings: Additional property relabelings is not
allowed
```

I have committed the CRD schema as it is generated by a Python scripts which also depends on `pyyaml`, so that keeps the Golang-based CI simple. This script has the advantage of adding `"additionalProperties": false` to the JSON schema (strict mode).

https://github.com/instrumenta/kubernetes-json-schema is a bit outdated, so I switched to https://github.com/yannh/kubernetes-json-schema. `kubeval` being also unmaintained, we may want to switch to https://github.com/yannh/kubeconform as well.

## Verification

Please see `ci/circleci: build` check

### CODE REVIEW

**Comment by maxbrunet** [comment]
hmm `$(CURDIR)` returns `go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}` in the CI, and `kubeval` does not seem to like the curly braces. I'm going to try with `kubeconform` and see it passes.

**Comment by metalmatze** [comment]
Is it be possible to have this additionally to kubeval?

**Comment by maxbrunet** [comment]
@metalmatze what is your concern? `kubeconform` is basically the same thing as `kubeval`, it is a maintained and improved version: https://github.com/yannh/kubeconform

I noticed `kube-prometheus` started using it, so I thought the team here would somewhat familiar with it as well: https://github.com/prometheus-operator/kube-prometheus/blob/8e5bf00c54e7e2c715ab805d729d0178fa0a6155/Makefile#L39-L42

---

Otherwise, I may be able to make `kubeval` work again. `working_directory` in the Circle CI config does not support any interpolation, hardcoding the org/repo names without curly braces should fix it:
https://github.com/thanos-io/kube-thanos/blob/32a21ed67af756aab0926142b2622e198e2e1733/.circleci/config.yml#L3

> In general, CircleCI does not support interpolating environment variable into build config. Values used are treated as literals.

https://circleci.com/docs/2.0/env-vars/#using-parameters-and-bash-environment

But there is also a bug in `kubeval`, it should not URL encode the file path given by `file://`.

**Review by kakkoyun — APPROVED** [review]
Amazing 💯 It's just beautiful! Thanks for the great contribution.

**Pull request merged**
