### PR TITLE
support alertmanager configuration and extra volumes for thanos ruler.

### PR DESCRIPTION
**Pull request by morvencao**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by clyang82** [comment]
cc @kakkoyun @metalmatze

**Comment by metalmatze** [comment]
LGTM if it works!

**Comment by kakkoyun** [comment]
Same here. It would be great if you could attach generated examples for the changes.

**Comment by morvencao** [comment]
@kakkoyun Another look^^ just added testing alerting configuration.

**Review by kakkoyun — APPROVED** [review]
LGTM

**Pull request merged**
