### PR TITLE
Make securityContext configurable

### PR DESCRIPTION
**Pull request by clyang82**
Part of fix for https://github.com/observatorium/operator/issues/51. Make the securityContext configurable so that we can configure different securityContext to fit for different platform (e.g.: OpenShift) 

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Looks ok, I wonder if we could abstract this to avoid repetitions, but it looks good so far!

**Comment by brancz** [comment]
I need to try this, but I think this breaks users with PodSecurityPolicies

**Comment by brancz** [comment]
Nevermind, looks like it works as expected. Sorry for the noise.

**Pull request merged**
