### PR TITLE
add "mkdir -p" so it can create parent folders

### PR DESCRIPTION
**Pull request by achede22**
add "mkdir -p" so it can create parent folders
avoid the following error:

+ rm -rf examples/all/manifests
+ mkdir examples/all/manifests
mkdir: cannot create directory ‘examples/all/manifests’: No such file or directory

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Review by squat — APPROVED** [review]
Thanks :)

**Comment by squat** [comment]
@achede22 please sign your commit and then we can merge this :)
Hint: `git commit amend --signoff`

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
@achede22 please sign the DCO and we can merge :)

**Comment by metalmatze** [comment]
Perfect! 👍 
Because we embed some files for ease in our README.md and we generate that, could you be so kind and run `make README.md` to update the README with your changes? Thanks!

**Comment by achede22** [comment]
> Perfect! +1 Because we embed some files for ease in our README.md and we generate that, could you be so kind and run `make README.md` to update the README with your changes? Thanks!

done!

**Comment by squat** [comment]
Hi @achede22 it looks like one of more of your commits doesn't have the DCO signed. Once you sign we can merge :) it might be easiest if you squash your commits, as then you'll only need to sign once.

**Pull request closed without merging**
