### PR TITLE
Rewrite the thanos-bucket component without ksonnet

### PR DESCRIPTION
**Pull request by metalmatze**
As you can see there are no changes in the examples/all so the output
generated is equal to before.

### CODE REVIEW

**Review by kakkoyun — COMMENTED** [review]
🥇 LGTM.

We just need to remove the import line, I believe. 
`local k = import 'ksonnet/ksonnet.beta.4/k.libsonnet';`

**Comment by metalmatze** [comment]
Yes, lol :smile:

**Review by kakkoyun — APPROVED** [review]

**Comment by yeya24** [comment]
I am curious abou the motivation behind this. So we don't want to use the ksonnet library anymore?

**Comment by metalmatze** [comment]
In the end this is about readability mostly. 
It's 10x easier for people to read and write this kind of code, whereas ksonnet only adds so much type safety. 
Over the last couple of years it became more and more obvious that we should focus on the first one and use some other tool to check the output. [kubeval](https://www.kubeval.com/) so far has been really helpful.

**Comment by yeya24** [comment]
That makes sense. Thank you!

**Pull request merged**
