### PR TITLE
WIP: Add flags as parameter

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

I would like to hear your opinions on this pattern. By using this pattern I'm aiming to easily configure the flags for Thanos containers and also ensure uniqueness of the given flags. In the current state, this will create problems with repetitive flags that we have for Thanos, hence I have marked it as WIP for now.

I have chosen the Store as an example here. I would like to apply the same pattern for all components.

### CODE REVIEW

**Comment by brancz** [comment]
It's entirely possible (and exists) that flags are repeatable, in its current state, this won't work entirely, however, you should be able to handle this appropriately by doing type checks.

**Comment by metalmatze** [comment]
Looking at it again, I'm wondering if these couple of out of the box flags should be all we support with this configuration style. Everything more exotic can be an overwrite. That's why we chose jsonnet to begin with. :thinking:

**Comment by kakkoyun** [comment]
Yes, this could be. We can have dedicated configuration fields for stores for example, since they are repeated flags. Overall it'd be good to come up with a neat way to configure a feature that corresponds directly to a flag. I'll entertain a couple of other ideas when I've some free time.

**Comment by brancz** [comment]
Maybe this is a wild idea, but if we moved the thanos sub-commands to a package we could write something that analyzes the registered flags on the command and generate some jsonnet code for it, that way we could get some "safety", but don't have to worry about keeping things up to date, and still have jsonnet merges to fall back to if we need to do something out of the ordinary. Just a wild thought :man_shrugging: .

**Comment by bwplotka** [comment]
> Maybe this is a wild idea, but if we moved the thanos sub-commands to a package we could write something that analyzes the registered flags on the command and generate some jsonnet code for it, that way we could get some "safety", but don't have to worry about keeping things up to date, and still have jsonnet merges to fall back to if we need to do something out of the ordinary. Just a wild thought .

Interesting thought.

I was exploring some of those thoughts as well in our attempt of official helm charts: https://github.com/thanos-io/thanos/issues/1820#issuecomment-752616653

**Pull request closed without merging**
